<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit85e9ebceae719cf285b93e2f1da1a52e
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'Facebook\\' => 9,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Facebook\\' => 
        array (
            0 => __DIR__ . '/..' . '/facebook/graph-sdk/src/Facebook',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit85e9ebceae719cf285b93e2f1da1a52e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit85e9ebceae719cf285b93e2f1da1a52e::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit85e9ebceae719cf285b93e2f1da1a52e::$classMap;

        }, null, ClassLoader::class);
    }
}
